// <auto-generated />
using System;
using BlogSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSistemi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogSistemi.Entities.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87607752-bd4f-498c-9c1c-efc5573d120d"),
                            CreateDate = new DateTime(2023, 11, 4, 15, 39, 59, 744, DateTimeKind.Local).AddTicks(5080),
                            Name = "Asp.Net Core"
                        },
                        new
                        {
                            Id = new Guid("fca52c48-c773-4f61-b892-0673234348dd"),
                            CreateDate = new DateTime(2023, 11, 4, 15, 39, 59, 744, DateTimeKind.Local).AddTicks(5098),
                            Name = "Net Core"
                        });
                });

            modelBuilder.Entity("BlogSistemi.Entities.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("863fc391-dc52-4b95-830c-817d387c221f"),
                            CategoryId = new Guid("87607752-bd4f-498c-9c1c-efc5573d120d"),
                            CreateDate = new DateTime(2023, 11, 4, 15, 39, 59, 744, DateTimeKind.Local).AddTicks(6057),
                            Description = "lorem ipsum dolor sit amet",
                            Image = "",
                            Name = "MVC PROJE 1"
                        },
                        new
                        {
                            Id = new Guid("b1b84af2-8651-46cb-a889-370641572024"),
                            CategoryId = new Guid("fca52c48-c773-4f61-b892-0673234348dd"),
                            CreateDate = new DateTime(2023, 11, 4, 15, 39, 59, 744, DateTimeKind.Local).AddTicks(6061),
                            Description = "lorem ipsum dolor sit amet",
                            Image = "",
                            Name = "MVC PROJE 2"
                        });
                });

            modelBuilder.Entity("BlogSistemi.Entities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogSistemi.Entities.Entities.Post", b =>
                {
                    b.HasOne("BlogSistemi.Entities.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogSistemi.Entities.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
